[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  REACT_APP_API_URL = "/.netlify/functions/api"

[[edge_functions]]
  function = "ai-chat"
  path = "/api/chat"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  framework = "create-react-app"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200